---
title: "데이터 분석 보고서"
output:
  html_document: default
  word_document: default
  pdf_document: default
---


##1.1. [마크다운이란?](https://gist.github.com/ihoneymon/652be052a0727ad59601)


###마크다운 문법 

문자 앞뒤에 *특수문자*를 넣으면 기울임체

문자 앞뒤에 **특수문자**를 넣으면 강조체

문자 앞뒤에 ~~특수문자~~를 넣으면 취소선

문자 앞뒤에 [특수문자](http://www.google.com)를 넣으면
하이퍼 링크를 만듭니다.

# 1단계 제목
## 2단계 제목
### 3단계 제목
#### 4단계 제목


1. 첫번째
2. 두번째
3. 세번째

<hr/>

데이터 앞부분 일부를 출력하려면 'head()'
`tail()`은 데이터 뒷부분 일부분을 출력



###코드와 함께 결과를 출력

```{r}
head(cars)

summary(cars)

library(ggplot2)
library(plotly)

qplot(data=mpg , x= drv , fill = drv)


p <- ggplot(data = mpg , aes(x=displ , y= hwy, col = drv))+geom_point()
ggplotly(p)


p <- ggplot(data=diamonds , aes (x=cut,fill = clarity))+geom_bar(position = "dodge")
ggplotly(p)
```

### 코드 없이 결과만 출력 
```{r pressure,echo=FALSE}
plot(pressure)
```

```{r}
a=c(1,2,3,4,5)
b=c(2,3,4,5,6)
c=c(3,4,5,6,7)
boxplot(a,b,c)
```

###표준정규분포 그리기
```{r}
X <-seq(-5, 5, length=101)
X
Y <- (1/sqrt(2*pi))*exp(-X^2/2)
Y
plot(X, Y, type="l", col="red")
Y1 <- dnorm(X, mean=0, sd=1)


```


###뉴욕의 1973년도 공기의 질을 측정한 airquality 데이터셋의 상관관계 분석

```{r}
str(airquality)
airquality_1 <- airquality[,c(1:4)]

str(airquality_1)
airquality_2 <- na.omit(airquality_1)
str(airquality_2)
airquality_cor <- cor(airquality_2)
# scatter plot matrix
library(corrplot) 
plot(airquality_2)
corrplot(airquality_cor, method="number")
corrplot(airquality_cor, method="circle")
corrplot(airquality_cor, 
          method="shade", # 색 입힌 사각형
          addshade="all", # 상관관계 방향선 제시
          # shade.col=NA, # 상관관계 방향선 미제시
          tl.col="red", # 라벨 색 지정
         tl.srt=30, # 위쪽 라벨 회전 각도
         diag=FALSE, # 대각선 값 미제시
         addCoef.col="black", # 상관계수 숫자 색
         order="FPC" # "FPC": First Principle Component
                      # "hclust" : hierarchical clustering
                      # "AOE" : Angular Order of Eigenvectors
          )


```